# This workflow automates the deploymet of Terraform configurations to Hetzner Cloud.
name: 'Terraform CI'

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

env:
  TF_VERSION: '1.6.6'
  TF_WORKING_DIR: './terraform/live'

jobs:
  terraform:
    name: 'Terraform Validate and Plan'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure Hetzner Token
        # if: env.HCLOUD_TOKEN != ''
        run: echo "TF_VAR_hcloud_token=${{ secrets.HCLOUD_TOKEN }}" >> $GITHUB_ENV

      - name: Configure GitHub Token
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Create dev.tfvars
        # if: env.HCLOUD_TOKEN != ''
        run: |
          cat > dev.tfvars << EOF
          hcloud_token = "${{ secrets.HCLOUD_TOKEN }}"
          location = "hil"
          server_type = "cpx21"
          environment = "dev"
          ssh_keys = ["Hetzner"]
          EOF

      - name: Terraform Init
        if: env.HCLOUD_TOKEN != ''
        run: terraform init
         
      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: env.HCLOUD_TOKEN != ''
        run: terraform plan -var-file="dev.tfvars" -no-color
        continue-on-error: true